version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "5301:53/tcp"
      - "5301:53/udp"
      - "8081:80/tcp"
    environment:
      TZ: "America/Sao_Paulo"
    volumes:
      - "./etc-pihole/:/etc/pihole/"
      - "./etc-dnsmasq.d/:/etc/dnsmasq.d/"
    restart: unless-stopped

  net_scanner:
    container_name: net_scanner
    build: .
    ports:
      - "5302:53/tcp"
      - "5302:53/udp"
      - "8082:80/tcp"
    environment:
      TZ: "America/Sao_Paulo"
    volumes:
      - "./app/:/app/"
    restart: unless-stopped